name: app_io
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.1+9

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8
  cloud_firestore: ^6.0.2
  cloud_functions: ^6.0.1
  http: ^1.2.2
  mask_text_input_formatter: ^2.9.0
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1
  firebase_storage: ^13.0.1
  image_picker: ^1.1.2
  firebase_messaging: ^16.0.1
  flutter_launcher_icons: ^0.14.1
  connectivity_plus: ^7.0.0
  lottie: ^3.1.3
  dropdown_button2: ^2.3.9
  flutter_colorpicker: ^1.1.0
  modal_side_sheet: ^0.0.1
  async: ^2.11.0
  flutter_holo_date_picker: ^2.0.0
  fl_chart: ^1.1.0
  syncfusion_flutter_datepicker: ^31.1.17
  bottom_navy_bar: ^6.1.0
  file_picker: ^10.1.9
  flutter_secure_storage: ^9.2.2
  shimmer: ^3.0.0
  flutter_local_notifications: ^19.2.1
  excel: ^4.0.6
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  open_file: ^3.5.10
  share_plus: ^12.0.0
  app_tracking_transparency: ^2.0.6
  flutter_spinkit: ^5.2.1
  crop_your_image: ^2.0.0
  google_maps_flutter: ^2.11.0
  flutter_map_location_picker: ^0.0.8
  geolocator: ^14.0.2
  geocoding: ^3.0.0
  google_places_flutter: ^2.1.0
  flutter_typeahead: ^5.2.0
  firebase_app_check: ^0.4.0+1
  record: ^6.0.0
  emoji_picker_flutter: ^4.3.0
  audioplayers: ^6.0.0
  video_player: ^2.10.0
  cached_network_image: ^3.3.2
  flutter_svg: ^2.1.0
  extended_image: ^10.0.1
  string_similarity: ^2.1.1
  fl_country_code_picker: ^0.1.9
  flutter_masked_text2: ^0.9.1
  image: ^4.2.0
  pdf: ^3.10.7
  printing: ^5.12.0
  intl: ^0.20.2
  audio_waveforms: ^1.3.0
  logger: ^2.6.1
  just_audio: ^0.10.4
  flutter_cache_manager: ^3.4.1
  responsive_navigation_bar: ^5.0.2
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  assets:
    - 'assets/images/reports/timbrado.png'
    - 'assets/images/icons/logo.png'
    - 'assets/images/icons/icon camera.png'
    - 'assets/images/icons/logoLight.png'
    - 'assets/images/icons/logoDark.png'
    - 'assets/images/icons/logoTransparente.png'
    - 'assets/images/icons/placeholder-whats.png'
    - 'assets/animations/no_internet.json'
    - 'assets/animations/confetti.json'
    - 'assets/animations/balloons.json'
    - 'assets/animations/congratulations.gif'
    - 'assets/images/tutorial/Detalhes.jpg'
    - 'assets/images/tutorial/Filtros.jpg'
    - 'assets/images/tutorial/Status.jpg'
    - 'assets/images/tutorial/WhatsApp.jpg'
    - 'assets/images/chats/mobile-escuro.webp'
    - 'assets/images/chats/mobile-claro.webp'
    - 'assets/images/covers/onboarding.webp'
    - 'assets/images/covers/central-atendimento.webp'
    - 'assets/images/covers/manual-cliente.webp'
    - 'assets/images/covers/checklist-lead.webp'
    - 'assets/images/covers/manual-criativos.webp'
    - 'assets/images/covers/contrato.webp'

  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf

    - family: BrandingSF
      fonts:
        - asset: assets/fonts/BrandingSF-Black.ttf
        - asset: assets/fonts/BrandingSF-Bold.ttf
        - asset: assets/fonts/BrandingSF-Medium.ttf
        - asset: assets/fonts/BrandingSF-SemiBold.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icons/logo.png" # Ícone do aplicativo
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icons/logo.png" # Ícone adaptativo para Android
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/icons/logo.png" # Ícone para web
    background_color: "#7000FF"
    theme_color: "#7000FF"
  windows:
    generate: true
    image_path: "assets/images/icons/logo.png" # Ícone para Windows
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icons/logo.png" # Ícone para macOS