// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx4PK6qJ808RewLurHS_6KYixVQ98OlU0',
    appId: '1:148670195922:web:1d70121879d973f975a50b',
    messagingSenderId: '148670195922',
    projectId: 'app-io-1c16f',
    authDomain: 'app-io-1c16f.firebaseapp.com',
    databaseURL: 'https://app-io-1c16f-default-rtdb.firebaseio.com',
    storageBucket: 'app-io-1c16f.appspot.com',
    measurementId: 'G-ED88PRTRY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6L9y8lq2jnVmxcQz6ygsvYC5mxREbnBs',
    appId: '1:148670195922:android:cd7b86c46ab4fc3c75a50b',
    messagingSenderId: '148670195922',
    projectId: 'app-io-1c16f',
    databaseURL: 'https://app-io-1c16f-default-rtdb.firebaseio.com',
    storageBucket: 'app-io-1c16f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR6YkiN9mjKccU121AQEUYAKgllmLeQqk',
    appId: '1:148670195922:ios:cfa0dfecb023c91775a50b',
    messagingSenderId: '148670195922',
    projectId: 'app-io-1c16f',
    databaseURL: 'https://app-io-1c16f-default-rtdb.firebaseio.com',
    storageBucket: 'app-io-1c16f.appspot.com',
    iosBundleId: 'com.example.appIoCerto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR6YkiN9mjKccU121AQEUYAKgllmLeQqk',
    appId: '1:148670195922:ios:40ed6ebf743c048975a50b',
    messagingSenderId: '148670195922',
    projectId: 'app-io-1c16f',
    databaseURL: 'https://app-io-1c16f-default-rtdb.firebaseio.com',
    storageBucket: 'app-io-1c16f.appspot.com',
    iosBundleId: 'com.example.appIo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx4PK6qJ808RewLurHS_6KYixVQ98OlU0',
    appId: '1:148670195922:web:3970f414e8b88a2175a50b',
    messagingSenderId: '148670195922',
    projectId: 'app-io-1c16f',
    authDomain: 'app-io-1c16f.firebaseapp.com',
    databaseURL: 'https://app-io-1c16f-default-rtdb.firebaseio.com',
    storageBucket: 'app-io-1c16f.appspot.com',
    measurementId: 'G-C2YMLM5ZD6',
  );

}